-- CreateEnum
CREATE TYPE "CreationState" AS ENUM ('DRAFT_BASICS', 'DRAFT_DESCRIPTION', 'DRAFT_TIERS', 'DRAFT_REQUIREMENTS', 'DRAFT_GALLERY', 'DRAFT_PUBLISH');

-- AlterTable
ALTER TABLE "Gig" ADD COLUMN     "creationState" "CreationState" NOT NULL DEFAULT 'DRAFT_BASICS';
