### Register Test
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "email": "seyiadebayo@lautech.edu.ng",
  "password": "SecurePassword123",
  "name": "Seyi Adebayo",
  "dateOfBirth": "2008-07-15",
  "university": "LAUTECH",
  "phoneNumber": "+2348012345678"
}

### Login Test
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "seyiadebayo@lautech.edu.ng",
  "password": "SecurePassword123"
}

eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI3MDljNDMwZS1kMzJhLTQ5NjQtYmY2OS00ZWQwN2IzMTU3OGEiLCJlbWFpbCI6InNleWlhZGViYXlvQGxhdXRlY2guZWR1Lm5nIiwicm9sZSI6IlNFTExFUiIsInRva2VuVmVyc2lvbiI6MCwiaWF0IjoxNzg1NDYxNTUwLCJleHAiOjE3ODYwNjYzNTB9.h1riYxIyk_OfbsPdeL-AWEYdcLrgE9ilIKttI6v2W6s
### Login BUYER
POST http://localhost:3000/api/auth/login
Content-Type: application/json


{
  "email": "irorun757@lautech.edu.ng",
  "password": "Irorun1608"
}

### Login BUYER
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "idania@lasu.edu.ng",
  "password": "AhmedIdan_717"
}

### Login BUYER
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "ola@uniben.edu.ng",
  "password": "Olaidan_717"
}



### Test Refresh Token Endpoint
POST http://localhost:8080/api/auth/refresh
Content-Type: application/json

{
  "token": "YOUR_ACTUAL_JWT_STRING_HERE"
}

// cc419fde-2c22-4b68-b25c-dc9fb39554d1



// ALL SELLERS TO Test

[
  {
    "email": "fatimah.adeleke@unilag.edu.ng",
    "password": "Test1234!",
    "name": "Fatimah Adeleke",
    "dateOfBirth": "2007-04-22",
    "university": "UNILAG",
    "phoneNumber": "+2348023456789"
  },
  {
    "email": "emeka.obi@ui.edu.ng",
    "password": "Test1234!",
    "name": "Chukwuemeka Obi",
    "dateOfBirth": "2008-11-05",
    "university": "UI",
    "phoneNumber": "+2348134567890"
  },
  {
    "email": "aisha.bello@unilorin.edu.ng",
    "password": "Test1234!",
    "name": "Aisha Bello",
    "dateOfBirth": "2009-01-19",
    "university": "UNILORIN",
    "phoneNumber": "+2347045678901"
  },
  {
    "email": "tunde.fashola@oauife.edu.ng",
    "password": "Test1234!",
    "name": "Tunde Fashola",
    "dateOfBirth": "2008-08-14",
    "university": "OAU",
    "phoneNumber": "+2349056789012"
  },
  {
    "email": "ngozi.eze@abu.edu.ng",
    "password": "Test1234!",
    "name": "Ngozi Eze",
    "dateOfBirth": "2007-06-30",
    "university": "ABU",
    "phoneNumber": "+2348167890123"
  }
]