-- CreateTable
CREATE TABLE "GigFAQ" (
    "id" TEXT NOT NULL,
    "gigId" TEXT NOT NULL,
    "question" TEXT NOT NULL,
    "answer" TEXT NOT NULL,
    "order" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "GigFAQ_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "GigFAQ" ADD CONSTRAINT "GigFAQ_gigId_fkey" FOREIGN KEY ("gigId") REFERENCES "Gig"("id") ON DELETE CASCADE ON UPDATE CASCADE;
